DROP TABLE IF EXISTS USER_MEMBERSHIP_INFO;
DROP TABLE IF EXISTS USER;



CREATE TABLE USER (
    USER_ID VARCHAR(25) PRIMARY KEY
);

CREATE TABLE USER_MEMBERSHIP_INFO(
    INFO_SEQ INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(25),
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID),
    MEMBERSHIP_TYPE VARCHAR(15) NOT NULL,
    START_DATE TIMESTAMP NOT NULL,
    POINT INT NOT NULL,
    MEMBERSHIP_STATUS VARCHAR(1) NOT NULL
);
